import type {Model} from './types';

// Scores are an editorial preview used to exercise the task-specific ranking engine.
// Product names and capability summaries are linked to official provider sources.
export const models:Model[]=[
 {id:'gpt-56-sol',name:'GPT-5.6 Sol',provider:'OpenAI',kind:'Frontier reasoning',summary:'OpenAI flagship for complex professional work, reasoning, coding, and tool use.',quality:98,speed:68,value:62,privacy:48,reliability:96,context:99,priceIn:5,priceOut:30,open:false,modalities:['Text','Vision','Tools'],best:['coding','research','agents'],weakness:'Premium pricing for routine workloads',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:4,accent:'#10a37f',sourceUrl:'https://developers.openai.com/api/docs/models',verification:'Official provider documentation'},
 {id:'gpt-56-terra',name:'GPT-5.6 Terra',provider:'OpenAI',kind:'Balanced reasoning',summary:'Balanced GPT-5.6 option designed to retain strong intelligence at lower cost.',quality:95,speed:78,value:84,privacy:48,reliability:94,context:99,priceIn:2.5,priceOut:15,open:false,modalities:['Text','Vision','Tools'],best:['coding','research','agents'],weakness:'Still more expensive than high-volume small models',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:3,accent:'#10a37f',sourceUrl:'https://developers.openai.com/api/docs/models',verification:'Official provider documentation'},
 {id:'gpt-56-luna',name:'GPT-5.6 Luna',provider:'OpenAI',kind:'Efficient reasoning',summary:'Cost-sensitive GPT-5.6 model for high-volume work with a large context window.',quality:91,speed:89,value:93,privacy:48,reliability:92,context:99,priceIn:1,priceOut:6,open:false,modalities:['Text','Vision','Tools'],best:['coding','writing','agents'],weakness:'Lower ceiling than Sol on the hardest tasks',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:5,accent:'#10a37f',sourceUrl:'https://developers.openai.com/api/docs/models',verification:'Official provider documentation'},
 {id:'claude-sonnet-5',name:'Claude Sonnet 5',provider:'Anthropic',kind:'Agentic language',summary:'Anthropic’s agentic Sonnet model for planning, coding, browsers, terminals, and long-running work.',quality:96,speed:82,value:86,privacy:50,reliability:95,context:94,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Tools'],best:['coding','writing','agents'],weakness:'Hosted model with provider-controlled availability',freshness:'Official announcement checked Jul 10, 2026',sourceCount:1,trend:7,accent:'#d97757',sourceUrl:'https://www.anthropic.com/news/claude-sonnet-5',verification:'Official provider announcement'},
 {id:'claude-opus-48',name:'Claude Opus 4.8',provider:'Anthropic',kind:'Premium reasoning',summary:'High-end Claude model focused on coding, agents, research, analysis, and professional work.',quality:97,speed:67,value:66,privacy:50,reliability:97,context:95,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Tools'],best:['coding','research','writing','agents'],weakness:'Premium tier is unnecessary for many everyday tasks',freshness:'Official announcement checked Jul 10, 2026',sourceCount:1,trend:3,accent:'#d97757',sourceUrl:'https://www.anthropic.com/news/claude-opus-4-8',verification:'Official provider announcement'},
 {id:'claude-fable-5',name:'Claude Fable 5',provider:'Anthropic',kind:'Frontier language',summary:'Anthropic frontier model positioned for difficult software, knowledge, vision, and scientific work.',quality:99,speed:57,value:54,privacy:50,reliability:96,context:96,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Tools'],best:['coding','research','agents'],weakness:'Frontier capability may carry higher cost and latency',freshness:'Official announcement checked Jul 10, 2026',sourceCount:1,trend:8,accent:'#d97757',sourceUrl:'https://www.anthropic.com/news/claude-fable-5-mythos-5',verification:'Official provider announcement'},
 {id:'gemini-35-flash',name:'Gemini 3.5 Flash',provider:'Google',kind:'Fast multimodal',summary:'Fast Gemini model built for agentic loops, multi-step workflows, and coding iterations at scale.',quality:94,speed:95,value:94,privacy:47,reliability:92,context:97,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Audio','Tools'],best:['coding','agents','research'],weakness:'Provider preview and stable aliases can change',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:8,accent:'#4285f4',sourceUrl:'https://ai.google.dev/gemini-api/docs/models/gemini-3.5-flash',verification:'Official provider documentation'},
 {id:'gemini-31-pro',name:'Gemini 3.1 Pro Preview',provider:'Google',kind:'Preview reasoning',summary:'Google reasoning model optimized for software engineering and reliable multi-step tool use.',quality:97,speed:72,value:75,privacy:47,reliability:93,context:99,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Audio','Video','Tools'],best:['coding','research','agents'],weakness:'Preview status means behavior and identifiers may change',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:4,accent:'#4285f4',sourceUrl:'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview',verification:'Official provider documentation'},
 {id:'gemini-25-flash-lite',name:'Gemini 2.5 Flash-Lite',provider:'Google',kind:'Budget multimodal',summary:'Google’s cost-efficient multimodal model for classification, extraction, and low-latency volume.',quality:83,speed:98,value:98,privacy:47,reliability:88,context:92,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Audio'],best:['writing','agents'],weakness:'Not intended for the most complex reasoning',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:0,accent:'#4285f4',sourceUrl:'https://ai.google.dev/gemini-api/docs/models/gemini-2.5-flash-lite',verification:'Official provider documentation'},
 {id:'gemini-deep-research',name:'Gemini Deep Research',provider:'Google',kind:'Research agent',summary:'Specialized Gemini research agent for autonomous, cited, multi-step investigations.',quality:96,speed:55,value:70,privacy:45,reliability:94,context:98,priceIn:0,priceOut:0,open:false,modalities:['Text','Files','Tools'],best:['research','agents'],weakness:'Specialized workflow rather than a general-purpose chat model',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:6,accent:'#4285f4',sourceUrl:'https://ai.google.dev/gemini-api/docs/models/deep-research-preview-04-2026',verification:'Official provider documentation'},
 {id:'grok-45',name:'Grok 4.5',provider:'xAI',kind:'Frontier reasoning',summary:'Latest Grok family entry listed by xAI for advanced text, reasoning, and tool-enabled workloads.',quality:95,speed:75,value:73,privacy:42,reliability:91,context:93,priceIn:0,priceOut:0,open:false,modalities:['Text','Vision','Tools'],best:['research','coding','agents'],weakness:'Independent evidence coverage is still developing',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:5,accent:'#18181b',sourceUrl:'https://docs.x.ai/docs/models',verification:'Official provider documentation'},
 {id:'grok-4-fast',name:'Grok 4 Fast',provider:'xAI',kind:'Fast reasoning',summary:'Lower-latency Grok variant offered in reasoning and non-reasoning configurations.',quality:90,speed:94,value:89,privacy:42,reliability:88,context:91,priceIn:0,priceOut:0,open:false,modalities:['Text','Tools'],best:['coding','agents','writing'],weakness:'Tradeoffs vary between reasoning modes',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:2,accent:'#18181b',sourceUrl:'https://docs.x.ai/docs/models/grok-4-fast-reasoning',verification:'Official provider documentation'},
 {id:'deepseek-v4-pro',name:'DeepSeek V4 Pro',provider:'DeepSeek',kind:'Open reasoning',summary:'Open model with thinking, tool calls, long context, and an API compatible with common SDK formats.',quality:95,speed:69,value:94,privacy:88,reliability:90,context:99,priceIn:0,priceOut:0,open:true,modalities:['Text','Tools'],best:['coding','research','local','agents'],weakness:'Self-hosting the full model requires substantial hardware',freshness:'Official docs checked Jul 10, 2026',sourceCount:2,trend:8,accent:'#4d6bfe',sourceUrl:'https://api-docs.deepseek.com/quick_start/pricing',verification:'Official provider documentation'},
 {id:'deepseek-v4-flash',name:'DeepSeek V4 Flash',provider:'DeepSeek',kind:'Efficient open reasoning',summary:'Fast, economical DeepSeek V4 option with thinking mode, tools, and long context.',quality:90,speed:93,value:98,privacy:90,reliability:88,context:99,priceIn:0,priceOut:0,open:true,modalities:['Text','Tools'],best:['coding','local','agents'],weakness:'Lower ceiling than the Pro variant',freshness:'Official docs checked Jul 10, 2026',sourceCount:2,trend:9,accent:'#4d6bfe',sourceUrl:'https://api-docs.deepseek.com/',verification:'Official provider documentation'},
 {id:'llama-4-maverick',name:'Llama 4 Maverick',provider:'Meta',kind:'Open multimodal',summary:'Open-weight multimodal mixture-of-experts model designed for capable, customizable deployments.',quality:88,speed:75,value:91,privacy:97,reliability:85,context:94,priceIn:0,priceOut:0,open:true,modalities:['Text','Vision'],best:['local','research','writing'],weakness:'Production deployment requires infrastructure expertise',freshness:'Official announcement checked Jul 10, 2026',sourceCount:1,trend:-1,accent:'#0668e1',sourceUrl:'https://ai.meta.com/blog/llama-4-multimodal-intelligence/',verification:'Official provider announcement'},
 {id:'llama-4-scout',name:'Llama 4 Scout',provider:'Meta',kind:'Efficient open multimodal',summary:'Efficient open-weight Llama 4 model designed to fit a single H100 with Int4 quantization.',quality:84,speed:86,value:95,privacy:98,reliability:83,context:98,priceIn:0,priceOut:0,open:true,modalities:['Text','Vision'],best:['local','writing','research'],weakness:'Quality trails larger frontier-hosted models',freshness:'Official announcement checked Jul 10, 2026',sourceCount:1,trend:0,accent:'#0668e1',sourceUrl:'https://ai.meta.com/blog/llama-4-multimodal-intelligence/',verification:'Official provider announcement'},
 {id:'mistral-medium-35',name:'Mistral Medium 3.5',provider:'Mistral AI',kind:'Open-weight generalist',summary:'Open-weight Mistral family model combining instruction following, reasoning, and coding.',quality:89,speed:77,value:92,privacy:96,reliability:86,context:90,priceIn:0,priceOut:0,open:true,modalities:['Text','Tools'],best:['local','coding','agents'],weakness:'Deployment requirements vary by quantization and host',freshness:'Official model page checked Jul 10, 2026',sourceCount:1,trend:4,accent:'#f59e0b',sourceUrl:'https://huggingface.co/mistralai',verification:'Official provider model repository'},
 {id:'command-a',name:'Command A',provider:'Cohere',kind:'Enterprise language',summary:'Cohere model family entry aimed at enterprise generation, retrieval, and tool-based applications.',quality:87,speed:80,value:84,privacy:78,reliability:90,context:91,priceIn:0,priceOut:0,open:false,modalities:['Text','Tools'],best:['research','agents','writing'],weakness:'Best fit is enterprise retrieval rather than every consumer task',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:0,accent:'#39594d',sourceUrl:'https://docs.cohere.com/docs/models',verification:'Official provider documentation'},
 {id:'gpt-image-2',name:'GPT Image 2',provider:'OpenAI',kind:'Image generation',summary:'OpenAI’s current state-of-the-art image generation and editing model.',quality:96,speed:79,value:78,privacy:46,reliability:94,context:35,priceIn:0,priceOut:0,open:false,modalities:['Image'],best:['images'],weakness:'Specialized for images rather than general reasoning',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:7,accent:'#10a37f',sourceUrl:'https://developers.openai.com/api/docs/models',verification:'Official provider documentation'},
 {id:'gemini-omni-flash',name:'Gemini Omni Flash',provider:'Google',kind:'Video generation preview',summary:'Conversational preview model for generating and editing video from text and images.',quality:91,speed:88,value:82,privacy:44,reliability:85,context:45,priceIn:0,priceOut:0,open:false,modalities:['Video','Image'],best:['video'],weakness:'Preview availability and behavior can change',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:9,accent:'#4285f4',sourceUrl:'https://ai.google.dev/gemini-api/docs/models/gemini-omni-flash',verification:'Official provider documentation'},
 {id:'gpt-realtime-21',name:'GPT-Realtime-2.1',provider:'OpenAI',kind:'Realtime voice',summary:'Realtime OpenAI model for low-latency speech, reasoning, and tool-enabled interactions.',quality:92,speed:98,value:78,privacy:45,reliability:93,context:55,priceIn:0,priceOut:0,open:false,modalities:['Audio','Text','Tools'],best:['audio','agents'],weakness:'Specialized realtime API integration required',freshness:'Official docs checked Jul 10, 2026',sourceCount:1,trend:6,accent:'#10a37f',sourceUrl:'https://developers.openai.com/api/docs/models',verification:'Official provider documentation'}
];

export const releases=[
 {date:'JUL 10',type:'CATALOG UPDATE',provider:'AI Compass',title:'Major provider catalog added',detail:'Official-source entries now cover OpenAI, Anthropic, Google, xAI, DeepSeek, Meta, Mistral, and Cohere.',verified:'Official sources linked'},
 {date:'JUN 30',type:'NEW MODEL',provider:'Anthropic',title:'Claude Sonnet 5 announced',detail:'Anthropic positions Sonnet 5 for agentic planning, coding, and tool use.',verified:'Official announcement'},
 {date:'JUN 30',type:'NEW MODEL',provider:'Google',title:'Gemini Omni Flash preview documented',detail:'Conversational video generation and editing enters preview.',verified:'Official documentation'},
 {date:'APR 24',type:'OPEN WEIGHTS',provider:'DeepSeek',title:'DeepSeek V4 Preview released',detail:'V4 Pro and Flash combine thinking, tools, and long context.',verified:'Official documentation'}
];

export const prompts=[
 {title:'Tool-use reliability pattern',model:'Multi-model',status:'Research prompt',verified:'Independently verified',lesson:'Explicit tool contracts reduce silent failure.'},
 {title:'Public assistant behavior spec',model:'Open models',status:'Official system prompt',verified:'Official',lesson:'Clear priority ordering improves instruction handling.'},
 {title:'Long-context retrieval study',model:'Multi-model',status:'Prompt design study',verified:'Public record',lesson:'Position and repetition change retrieval accuracy.'}
];
