import type {Model} from './types';
export const models:Model[]=[
 {id:'atlas-reason',name:'Atlas Reason',provider:'Northstar AI',kind:'Reasoning',summary:'Premium reasoning model for difficult software and research workflows.',quality:96,speed:62,value:68,privacy:42,reliability:94,context:91,priceIn:3,priceOut:15,open:false,modalities:['Text','Vision','Tools'],best:['coding','research','agents'],weakness:'Premium output pricing',freshness:'Verified 2 days ago',sourceCount:9,trend:2,accent:'#635bff'},
 {id:'swift-mini',name:'Swift Mini',provider:'Kestrel Labs',kind:'Fast language',summary:'Low-latency general model with unusually strong capability per dollar.',quality:82,speed:97,value:96,privacy:48,reliability:88,context:72,priceIn:.18,priceOut:.72,open:false,modalities:['Text','Vision','Tools'],best:['coding','writing','agents'],weakness:'Less reliable on long reasoning chains',freshness:'Verified 5 days ago',sourceCount:7,trend:4,accent:'#0d9488'},
 {id:'cedar-70b',name:'Cedar 70B Open',provider:'Cedar Research',kind:'Open-weight',summary:'Strong self-hostable model with flexible deployment and a permissive license.',quality:87,speed:55,value:84,privacy:98,reliability:82,context:76,priceIn:0,priceOut:0,open:true,modalities:['Text','Tools'],best:['local','privacy','coding'],weakness:'Requires capable local hardware',freshness:'Verified 8 days ago',sourceCount:11,trend:1,accent:'#ca8a04'},
 {id:'muse-pro',name:'Muse Pro',provider:'Lumen',kind:'Creative language',summary:'Natural prose, precise editing, and nuanced long-form creative direction.',quality:91,speed:76,value:73,privacy:45,reliability:90,context:88,priceIn:2.5,priceOut:12,open:false,modalities:['Text','Vision'],best:['writing','research'],weakness:'No local deployment',freshness:'Verified yesterday',sourceCount:8,trend:-1,accent:'#db2777'},
 {id:'prism-image',name:'Prism Image 4',provider:'Lumen',kind:'Image',summary:'High-fidelity image generation with excellent prompt adherence and typography.',quality:94,speed:70,value:77,privacy:40,reliability:91,context:35,priceIn:.04,priceOut:.08,open:false,modalities:['Image'],best:['images'],weakness:'Limited edit controls via API',freshness:'Verified 3 days ago',sourceCount:6,trend:3,accent:'#9333ea'},
 {id:'motion-one',name:'Motion One',provider:'Kinetic',kind:'Video',summary:'Controllable short-form video generation with strong motion consistency.',quality:89,speed:58,value:61,privacy:39,reliability:84,context:30,priceIn:.1,priceOut:.5,open:false,modalities:['Video','Audio'],best:['video'],weakness:'Expensive at high resolution',freshness:'Verified 6 days ago',sourceCount:5,trend:6,accent:'#e11d48'},
 {id:'echo-voice',name:'Echo Voice',provider:'Resonance',kind:'Audio',summary:'Expressive low-latency speech and transcription for realtime applications.',quality:88,speed:95,value:87,privacy:54,reliability:93,context:20,priceIn:.06,priceOut:.24,open:false,modalities:['Audio'],best:['audio','agents'],weakness:'Voice cloning requires consent review',freshness:'Verified 4 days ago',sourceCount:8,trend:0,accent:'#0284c7'}
];
export const releases=[
 {date:'JUL 09',type:'PRICE CHANGE',provider:'Kestrel Labs',title:'Swift Mini output pricing reduced 20%',detail:'Lower costs strengthen its position for high-volume automation.',verified:'Official source'},
 {date:'JUL 08',type:'NEW MODEL',provider:'Lumen',title:'Prism Image 4 enters public API',detail:'Improved typography and multi-reference consistency.',verified:'Official + tested'},
 {date:'JUL 06',type:'OPEN WEIGHTS',provider:'Cedar Research',title:'Cedar 70B weights released',detail:'Permissive deployment terms with new 4-bit quantizations.',verified:'Independently verified'},
 {date:'JUL 03',type:'BENCHMARK',provider:'Northstar AI',title:'Atlas Reason gains in coding reliability',detail:'Three independent suites show fewer tool-use failures.',verified:'3 independent sources'}
];
export const prompts=[
 {title:'Tool-use reliability pattern',model:'Multi-model',status:'Research prompt',verified:'Independently verified',lesson:'Explicit tool contracts reduce silent failure.'},
 {title:'Public assistant behavior spec',model:'Cedar 70B',status:'Official system prompt',verified:'Official',lesson:'Clear priority ordering improves instruction handling.'},
 {title:'Long-context retrieval study',model:'Atlas Reason',status:'Prompt design study',verified:'Public record',lesson:'Position and repetition change retrieval accuracy.'}
];
